# ~/.config/mise/config.toml
#
# Global mise config.
# This controls machine-wide mise behavior.

[tools]
node = "lts"
python = "latest"
bun = "latest"
rust = "latest"

[settings]
# Automatically install missing tool versions when a project/global config asks for them.
auto_install = true

# TODO: See if i want to enable
# idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
